version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: todo_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: ./  # The root of your project (where docker-compose.yml is located)
      dockerfile: Dockerfile  # Path to your custom Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: todo_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432

volumes:
  postgres_data:
    driver: local
